#!/bin/bash

files=$(ls ./sql/*.sql 2> /dev/null | wc -l)
if [ "$files" != "0" ]
then

	for file in ./sql/*.sql

	do

		mysql -h 31.220.17.16 -D raceresu_Final2015 -u raceresu_final -pgravel1568  <${file}
		mv ${file} ./sql/archive

	done

fi
